class Book {
  final String name;
  final String model;
  final String brand;
  final String imageUrl;
  final String imageUrl1;
  final String imageUrl2;
  final String description;
  final String speed;
  final String seats;
  final String engine;
  final String stars;
  final double price;
  final double priceW;
  final double priceM;
  final String date;
  final String mileage;
  final String color;
  final String trans;
  final String fuel;
  final String cc;
  final String color1;
  final String color2;
  final String color3;
  final String location;
  final double coord1;
  final double coord2;
  final String chooseC1;
  final String chooseC2;
  final String chooseC3;

  const Book(
      {required this.name,
      required this.brand,
      required this.model,
      required this.imageUrl,
      required this.imageUrl1,
      required this.imageUrl2,
      required this.description,
      required this.speed,
      required this.seats,
      required this.engine,
      required this.stars,
      required this.price,
      required this.priceW,
      required this.priceM,
      required this.date,
      required this.mileage,
      required this.color,
      required this.trans,
      required this.fuel,
      required this.cc,
      required this.color1,
      required this.color2,
      required this.color3,
      required this.location,
      required this.coord1,
      required this.coord2,
      required this.chooseC1,
      required this.chooseC2,
      required this.chooseC3});
}

const allBooks = [
  Book(
    brand: 'assets/images/toyotalogo.png',
    model: 'Vitz XP10',
    name: 'Toyota',
    location:
        'The Mauritius Co-operative Agricultural Federation Ltd - Branch Union Park',
    imageUrl: 'assets/images/toyotavitz.png',
    imageUrl1: 'assets/images/toyotavitz1.png',
    imageUrl2: 'assets/images/toyotavitz2.png',
    description:
        'With a curb weight of 2072 lbs (940 kgs), the Vitz XP10 1.5RS has a naturally-aspirated Inline 4 cylinder engine, Petrol motor, with the engine code 1NZ-FE.',
    speed: '215 km/h',
    seats: '5',
    engine: '1.5 RS',
    stars: '4.5',
    price: 1000,
    priceW: 6350,
    priceM: 25400,
    date: '2007',
    mileage: '250,000 Km',
    trans: 'Manual',
    fuel: 'Petrol',
    cc: '1298',
    color: 'Yellow',
    color1: 'assets/images/red.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/orange.png',
    coord1: -20.38978990371461,
    coord2: 57.58359178975668,
    chooseC1: 'assets/images/toyotavitzc1.png',
    chooseC2: 'assets/images/toyotavitzc2.png',
    chooseC3: 'assets/images/toyotavitzc3.png',
  ),
  Book(
    brand: 'assets/images/hondalogo.png',
    model: 'Fit 2020',
    name: 'Honda',
    location: 'Wazaabi Sushi Beau Bassin, Barkly Street, Beau Bassin-Rose Hill',
    imageUrl: 'assets/images/hondafit.png',
    imageUrl1: 'assets/images/hondafit1.png',
    imageUrl2: 'assets/images/hondafit2.png',
    description:
        'The Honda Fit is a front-wheel-drive hatchback that seats up to five. It has a 130-horsepower, 1.5-liter four-cylinder engine that pairs with a six-speed manual or continuously variable automatic transmission',
    speed: '300 km/h',
    seats: '5',
    engine: '1.5 N15',
    stars: '4.7',
    price: 1200,
    priceW: 6000,
    priceM: 24000,
    date: '2012',
    mileage: '150,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '1498',
    color: 'Black',
    color1: 'assets/images/green.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/purple.png',
    coord1: -20.22560187754515,
    coord2: 57.46434173507876,
    chooseC1: 'assets/images/hondafitc1.png',
    chooseC2: 'assets/images/hondafitc2.png',
    chooseC3: 'assets/images/hondafitc3.png',
  ),
  Book(
    brand: 'assets/images/bmwlogo.png',
    model: '3 Series Sedan E36',
    name: 'BMW',
    location: 'Car Rental Rose Belle, Saint Jean Road',
    imageUrl: 'assets/images/bmwe36.png',
    imageUrl1: 'assets/images/bmwe361.png',
    imageUrl2: 'assets/images/bmwe362.png',
    description:
        'The M3 E36 was designed with the engine in mind. With its debut, a 6-cylinder in-line engine made its debut in a 3-Series top model. From the outset, the characteristic and BMW-typical S50B30 naturally aspirated engine combined the best of both worlds. A silky, turbine-like run was at the top of the specifications, especially at a partial load. Nevertheless, its heart should be emotional and feel like an uncompromising racing engine. After a very short time, experts and sports car enthusiasts all over the world were convinced that the engineers at BMW M GmbH had achieved this aim in full.',
    speed: '280 km/h',
    seats: '5',
    engine: 'S50',
    stars: '4.3',
    price: 1300,
    priceW: 8750,
    priceM: 34500,
    date: '1996',
    mileage: '330,000 Km',
    trans: 'Manual',
    fuel: 'Petrol',
    cc: '2800',
    color: 'Blue',
    color1: 'assets/images/red.png',
    color2: 'assets/images/black.png',
    color3: 'assets/images/white.png',
    coord1: -20.21569894170751,
    coord2: 57.46966953438571,
    chooseC1: 'assets/images/bmwe36c1.png',
    chooseC2: 'assets/images/bmwe36c2.png',
    chooseC3: 'assets/images/bmwe36c3.png',
  ),
  Book(
    brand: 'assets/images/mazdalogo.png',
    model: '3 2016',
    name: 'Mazda',
    location: 'Car Rental Rose Belle, Saint Jean Road',
    imageUrl: 'assets/images/mazda3.png',
    imageUrl1: 'assets/images/mazda31.png',
    imageUrl2: 'assets/images/mazda32.png',
    description:
        'For the 2016 Mazda 3, the SV trim level has been dropped, so the 3i Sport trim is now the base model. Mazda has also added more standard features this year. A rearview camera is on every Mazda 3, while automatic headlights, automatic wipers and a sunroof are standard on trim levels higher than Sport.',
    speed: '220 km/h',
    seats: '5',
    engine: '1.5 L4',
    stars: '4.2',
    price: 1350,
    priceW: 9100,
    priceM: 36350,
    date: '2016',
    mileage: '145,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '1500',
    color: 'Red',
    color1: 'assets/images/green.png',
    color2: 'assets/images/black.png',
    color3: 'assets/images/yellow.png',
    coord1: -20.21569894170751,
    coord2: 57.46966953438571,
    chooseC1: 'assets/images/mazda3c1.png',
    chooseC2: 'assets/images/mazda3c2.png',
    chooseC3: 'assets/images/mazda3c3.png',
  ),
  Book(
    brand: 'assets/images/toyotalogo.png',
    model: 'Aqua NHP10',
    name: 'Toyota',
    location: 'Sixt Rent a Car — Quatre Bornes, Quatre Bornes, Mauritius',
    imageUrl: 'assets/images/toyotaaqua.png',
    imageUrl1: 'assets/images/toyotaaqua1.png',
    imageUrl2: 'assets/images/toyotaaqua2.png',
    description:
        'The Toyota Aqua is a popular used car among kiwi buyers. It’s a compact, front-wheel-drive, hybrid hatchback that the Japanese manufacturer first launched back in December 2011.',
    speed: '180 km/h',
    seats: '5',
    engine: '1,5 XP21',
    stars: '4.9',
    price: 1200,
    priceW: 8300,
    priceM: 33500,
    date: '2015',
    mileage: '74,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '1500',
    color: 'Green',
    color1: 'assets/images/white.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/pink.png',
    coord1: -20.266947124690134,
    coord2: 57.47673685281009,
    chooseC1: 'assets/images/toyotaaquac3.png',
    chooseC2: 'assets/images/toyotaaquac1.png',
    chooseC3: 'assets/images/toyotaaquac2.png',
  ),
  Book(
    brand: 'assets/images/toyotalogo.png',
    model: '',
    name: 'Toyota Prius',
    location:
        'The Mauritius Co-operative Agricultural Federation Ltd - Branch Union Park',
    imageUrl: 'assets/images/toyotaprius.png',
    imageUrl1: 'assets/images/toyotaprius1.png',
    imageUrl2: 'assets/images/toyotaprius2.png',
    description:
        'The 2011 Prius can also seemingly transform from a versatile utility hatchback to a small, hyper-efficient luxury sedan depending on how you equip it. On the higher trim levels you will find high-end appointments like heated leather seats, a solar-powered sunroof (it ventilates the interior when parked), a navigation system, adaptive cruise control (it matches your speed to the car ahead), a pre-collision system (tightens seatbelts and applies the brakes if a crash is unavoidable) and a lane-departure warning system. ',
    speed: '200 km/h',
    seats: '5',
    engine: '2.0 M20A',
    stars: '4.1',
    price: 900,
    priceW: 6250,
    priceM: 24000,
    date: '2011',
    mileage: '215,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '2000',
    color: 'Super White',
    color1: 'assets/images/black.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/green.png',
    coord1: -20.389815045230005,
    coord2: 57.583720535084694,
    chooseC1: 'assets/images/toyotapriusc2.png',
    chooseC2: 'assets/images/toyotapriusc1.png',
    chooseC3: 'assets/images/toyotapriusc3.png',
  ),
  Book(
    brand: 'assets/images/kialogo.png',
    model: 'Picanto 2019',
    name: 'Kia',
    location: 'Winner\'s Vacoas, Vacoas-Phoenix',
    imageUrl: 'assets/images/kiapicanto.png',
    imageUrl1: 'assets/images/kiapicanto1.png',
    imageUrl2: 'assets/images/kiapicanto2.png',
    description:
        'As with many Kias, the transformation of the Picanto from the drab and sparse first generation car to this Mk3 model is a big one. Building on the stylish design of the Picanto Mk2, the South Korean city car delivers a higher quality and better equipped interior, more space, a grown-up driving experience and extra personalisation. Kia even offers an SUV-style X-Line model for those after the crossover look.',
    speed: '180 km/h',
    seats: '5',
    engine: '1.2 AO',
    stars: '4.8',
    price: 1100,
    priceW: 7500,
    priceM: 29000,
    date: '2019',
    mileage: '1 week',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '1200',
    color: 'Grey',
    color1: 'assets/images/red.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/black.png',
    coord1: -20.30788760169488,
    coord2: 57.49326825109191,
    chooseC1: 'assets/images/kiapicantoc1.png',
    chooseC2: 'assets/images/kiapicantoc2.png',
    chooseC3: 'assets/images/kiapicantoc3.png',
  ),
  Book(
    brand: 'assets/images/SUZUKILOGO.png',
    model: 'Alto K10',
    name: 'Suzuki',
    location: 'Sixt Rent a Car — Quatre Bornes, Quatre Bornes, Mauritius',
    imageUrl: 'assets/images/suzukialto.png',
    imageUrl1: 'assets/images/suzukialto1.png',
    imageUrl2: 'assets/images/suzukialto2.png',
    description:
        'The Alto K10 is powered by a one-litre, three-cylinder, all-aluminium motor that is now the mainstay of Maruti’s entry-level range. The new engine has been updated to meet the latest emission norms, including the stricter BS6 Phase 2 standards, which come into effect next April. The Alto K10 comes with two transmission options, a five-speed manual and a five-speed automated manual transmission which Maruti calls AGS (for Auto Gear Shift). The manual makes the most of the feisty 67hp motor ',
    speed: '160 Km/h',
    seats: '5',
    engine: '1.0 K10C',
    stars: '3.9',
    price: 900,
    priceW: 6200,
    priceM: 24000,
    date: '2016',
    mileage: '120,000 Km',
    trans: 'Manual',
    fuel: 'Petrol',
    cc: '990',
    color: 'Red',
    color1: 'assets/images/blue.png',
    color2: 'assets/images/black.png',
    color3: 'assets/images/white.png',
    coord1: -20.266987383093035,
    coord2: 57.47672612397425,
    chooseC1: 'assets/images/suzukialtoc1.png',
    chooseC2: 'assets/images/suzukialtoc2.png',
    chooseC3: 'assets/images/suzukialtoc3.png',
  ),
  Book(
    brand: 'assets/images/nissanlogo.png',
    model: 'Micra 2015',
    name: 'Nissan',
    location:
        'Archery CSSC Clubhouse (Curepipe Starlight Sporting Club), Curepipe',
    imageUrl: 'assets/images/nissanmicra.png',
    imageUrl1: 'assets/images/nissanmicra1.png',
    imageUrl2: 'assets/images/nissanmicra2.png',
    description:
        'Nissan heavily revised fourth generation Micra supermini turned over a new leaf in 2013. As before, it was impressively space efficient and offered the option of a clever supercharged 1.2-litre petrol engine that was not only eager but also both frugal and green. It may be sensible rather than sporty, but this very affordable contender delivers in exactly the areas a small car should.',
    speed: '200 Km/h',
    seats: '5',
    engine: '1.2 HR12',
    stars: '4.7',
    price: 1100,
    priceW: 7600,
    priceM: 30350,
    date: '2015',
    mileage: '215,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '1200',
    color: 'Black',
    color1: 'assets/images/red.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/green.png',
    coord1: -20.333864355693116,
    coord2: 57.5055155313806,
    chooseC1: 'assets/images/nissanmicrac1.png',
    chooseC2: 'assets/images/nissanmicrac2.png',
    chooseC3: 'assets/images/nissanmicrac3.png',
  ),
  Book(
    brand: 'assets/images/hyundailogo.png',
    model: 'Creta N Line 2023',
    name: 'Hyundai',
    location: 'Bassin Carangue Little Beach, L\'Escalier',
    imageUrl: 'assets/images/hyundaikreta.png',
    imageUrl1: 'assets/images/hyundaikreta1.png',
    imageUrl2: 'assets/images/hyundaikreta2.png',
    description:
        'Creta is an all-rounder car and the best in the segment. Diesel mileage is around 24 on the highway. Performance is very good on hills. The suspension setup is better than seltos. The cabin is very silent with good insulation. The only problem is that the 8 inches screen does not come with wired Apple car play. Using wireless car play is not efficient every time.',
    speed: '280 km/h',
    seats: '5',
    engine: '1.5 M.P.I',
    stars: '4.3',
    price: 1500,
    priceW: 10000,
    priceM: 39000,
    date: '2023',
    mileage: '56,000 Km',
    trans: 'Automatic',
    fuel: 'Diesel',
    cc: '1500',
    color: 'White',
    color1: 'assets/images/orange.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/black.png',
    coord1: -20.49498448428951,
    coord2: 57.62333866392427,
    chooseC1: 'assets/images/hyundaikretac1.png',
    chooseC2: 'assets/images/hyundaikretac2.png',
    chooseC3: 'assets/images/hyundaikretac3.png',
  ),
  Book(
    brand: 'assets/images/mitsulogo.png',
    model: 'L200 Barbarian SVP',
    name: 'Mitsubushi',
    location: 'Chamarel Pumping station, Chamarel',
    imageUrl: 'assets/images/mitsul200.png',
    imageUrl1: 'assets/images/mitsul2001.png',
    imageUrl2: 'assets/images/mitsul2002.png',
    description:
        'This L200 first went on sale in September 2015, as the first of seven new-generation pickups launched between 2015 and 2017. And it set the standard high, with impressive fuel economy, good off-road ability and a whole host of safety systems.',
    speed: '230 km/h',
    seats: '5',
    engine: '2.4 FINJ',
    stars: '4.9',
    price: 2500,
    priceW: 14000,
    priceM: 55000,
    date: '2016',
    mileage: '170,000 Km',
    trans: 'Manual',
    fuel: 'Petrol',
    cc: '2400',
    color: 'Blue',
    color1: 'assets/images/red.png',
    color2: 'assets/images/pink.png',
    color3: 'assets/images/green.png',
    coord1: -20.428816699947646,
    coord2: 57.39327136021989,
    chooseC1: 'assets/images/mitsul200c1.png',
    chooseC2: 'assets/images/mitsul200c2.png',
    chooseC3: 'assets/images/mitsul200c3.png',
  ),
  Book(
    brand: 'assets/images/peugeotlogo.png',
    name: 'Peugeot',
    model: '2008 GT Line',
    location: 'Bois-Cheri Football Field, Bois Cheri Road, Bois Cheri',
    imageUrl: 'assets/images/peugeot2008.png',
    imageUrl1: 'assets/images/peugeot20082.png',
    imageUrl2: 'assets/images/peugeot20083.png',
    description:
        'It is a little. Are you sitting down? The petrol GT will set you back a whopping £31,350, a whisker under £500 a month if you opt for finance. Peugeot’s thrown everything at the top-spec model, with wireless phone charging, panoramic sunroof, adaptive cruise control with lane-keep assist, keyless entry and a host of other goodies.',
    speed: '200 km/h',
    seats: '5',
    engine: '1.2 3E',
    stars: '4.9',
    price: 1350,
    priceW: 9400,
    priceM: 37500,
    date: '2008',
    mileage: '230,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '1200',
    color: 'Orange',
    color1: 'assets/images/red.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/grey.png',
    coord1: -20.429626862998106,
    coord2: 57.53719210625013,
    chooseC1: 'assets/images/peugeot2008c1.png',
    chooseC2: 'assets/images/peugeot2008c2.png',
    chooseC3: 'assets/images/peugeot2008c3.png',
  ),
  Book(
    brand: 'assets/images/toyotalogo.png',
    name: 'Toyota',
    model: 'Fortuner 2021',
    location: 'Bois-Cheri Football Field, Bois Cheri Road, Bois Cheri',
    imageUrl: 'assets/images/toyotafortuner.png',
    imageUrl1: 'assets/images/toyotafortuner1.png',
    imageUrl2: 'assets/images/toyotafortuner2.png',
    description:
        'The 2.8-litre diesel has been refreshed a little and now makes 150kW at 3400rpm and 500Nm between 1600–2800rpm. The engine is paired with an Aisin six-speed automatic, which according to Toyota has been recalibrated to deliver more frequent torque converter lock-up. In theory that should make the Fortuner more efficient, run cooler, and sharpen up punch off the mark.',
    speed: '215 km/h',
    seats: '7',
    engine: '2.8 2XZ',
    stars: '4.3',
    price: 2400,
    priceW: 16500,
    priceM: 66000,
    date: '2021',
    mileage: '125000 Km',
    trans: 'Automatic',
    fuel: 'Diesel',
    cc: '4800',
    color: 'Red',
    color1: 'assets/images/black.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/green.png',
    coord1: -20.429626862998106,
    coord2: 57.53719210625013,
    chooseC1: 'assets/images/toyotafortunerc1.png',
    chooseC2: 'assets/images/toyotafortunerc2.png',
    chooseC3: 'assets/images/toyotafortunerc3.png',
  ),
  Book(
    brand: 'assets/images/mercedeslogo.png',
    name: 'Mercedes',
    model: 'AMG c63',
    location: 'MoVacances car Rentals, Bois Cheri',
    imageUrl: 'assets/images/mercedesc63.png',
    imageUrl1: 'assets/images/mercedesc631.png',
    imageUrl2: 'assets/images/mercedesc632.png',
    description:
        'An uprated version of the AMG A45’s 2.0-litre turbo engine claims to be the world’s most powerful production four-cylinder – with 469bhp – and pairs with an electric motor for peak outputs of 671bhp and 752lb ft. Numbers which could genuinely belong in a supercar and with a 3.4-second 0-62mph sprint to match. But there’s a figure here that doesn’t belong in that realm: launching simultaneously as a saloon and estate, neither C63 can be called slender, tipping the scales at 2,165 and 2,190 kilos respectively. Its purely petrol predecessor weighs around half a tonne less. ',
    speed: '250 km/h',
    seats: '5',
    engine: '6.2 V8',
    stars: '5.0',
    price: 5000,
    priceW: 35000,
    priceM: 120000,
    date: '2018',
    mileage: '50,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '6200',
    color: 'Black',
    color1: 'assets/images/red.png',
    color2: 'assets/images/grey.png',
    color3: 'assets/images/white.png',
    coord1: -20.426526022160974,
    coord2: 57.54191268165174,
    chooseC1: 'assets/images/mercedesc63c1.png',
    chooseC2: 'assets/images/mercedesc63c2.png',
    chooseC3: 'assets/images/mercedesc63c3.png',
  ),
  Book(
    brand: 'assets/images/hondalogo.png',
    name: 'Honda',
    model: 'Civic 2021',
    location: 'Britannia Village Hall, Britannia',
    imageUrl: 'assets/images/hondacivic.png',
    imageUrl1: 'assets/images/hondacivic1.png',
    imageUrl2: 'assets/images/hondacivic2.png',
    description:
        'Once mere basic transportation, the humble Honda Civic has blossomed into a desirable and fun-to-drive compact car. Available as either a sedan or a practical hatchback, the Civic is powered by your choice of a 158-hp 2.0-liter four-cylinder or a turbocharged 1.5-liter that makes up to 180 horsepower. Honda loads up its smallest car with plenty of standard driver-assistance features, including adaptive cruise control and lane-keeping assist. ',
    speed: '210 km/h',
    seats: '5',
    engine: '2.0 K20A',
    stars: '4.7',
    price: 1500,
    priceW: 10000,
    priceM: 38000,
    date: '2021',
    mileage: '70,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '2000',
    color: 'White',
    color1: 'assets/images/orange.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/red.png',
    coord1: -20.449644948732814,
    coord2: 57.563491140713076,
    chooseC1: 'assets/images/hondacivicc1.png',
    chooseC2: 'assets/images/hondacivicc2.png',
    chooseC3: 'assets/images/hondacivicc3.png',
  ),
  Book(
    brand: 'assets/images/v.png',
    name: 'Volkswagen',
    model: 'Tiguan 2023',
    location: 'Britannia Village Hall, Britannia',
    imageUrl: 'assets/images/volktiguan.png',
    imageUrl1: 'assets/images/volktiguan1.png',
    imageUrl2: 'assets/images/volktiguan2.png',
    description:
        'Thats especially true this year. Updates include sharper styling, improved interior materials, more standard technology features, and wider availability of advanced driver assist systems. Volkswagen also simplifies the Tiguan lineup and reduces the price of the top-trim version. Still available for the 2022 Tiguan is a third-row seat. It is cramped but can come in handy on those occasions when you need to take along extra passengers.',
    speed: '315 km/h',
    seats: '7',
    engine: '2.0 T.S.I',
    stars: '4.9',
    price: 1200,
    priceW: 8300,
    priceM: 31000,
    date: '2023',
    mileage: '10,000 km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '2000',
    color: 'White',
    color1: 'assets/images/black.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/yellow.png',
    coord1: -20.449644948732814,
    coord2: 57.563491140713076,
    chooseC1: 'assets/images/volktiguanc1.png',
    chooseC2: 'assets/images/volktiguanc2.png',
    chooseC3: 'assets/images/volktiguanc3.png',
  ),
  Book(
    brand: 'assets/images/v.png',
    name: 'Volkswagen',
    model: 'Bora 2005',
    location: 'Vivéa Business Park, Moka',
    imageUrl: 'assets/images/volkbora.png',
    imageUrl1: 'assets/images/volkbora1.png',
    imageUrl2: 'assets/images/volkbora2.png',
    description:
        'The Yanks cannot get enough of the booted Bora, outselling the hatchback Golf three to one, yet over here the trickle of Boras leaving Volkswagen showrooms is engulfed by the tidal wave of Golf variants.Standard features on all trim levels include air conditioning, anti-lock brakes, power assisted steering, twin airbags plus front seat side airbags, electric windows and door mirrors and central locking.',
    speed: '210 km/h',
    seats: '5',
    engine: '2.0 G',
    stars: '4.7',
    price: 1000,
    priceW: 6500,
    priceM: 29000,
    date: '2005',
    mileage: '50,000 Km',
    trans: 'Manual',
    fuel: 'Petrol',
    cc: '1200',
    color: 'Grey',
    color1: 'assets/images/red.png',
    color2: 'assets/images/yellow.png',
    color3: 'assets/images/black.png',
    coord1: -20.223692000647596,
    coord2: 57.53160568295999,
    chooseC1: 'assets/images/volkborac1.png',
    chooseC2: 'assets/images/volkborac2.png',
    chooseC3: 'assets/images/volkborac3.png',
  ),
  Book(
    brand: 'assets/images/porschelogo.png',
    name: 'Porsche',
    model: '911 Turbo S Coupe',
    location: 'MoVacances car Rentals, Bois Cheri',
    imageUrl: 'assets/images/porsche911.png',
    imageUrl1: 'assets/images/porsche9111.png',
    imageUrl2: 'assets/images/porsche9112.png',
    description:
        'The 2021 Porsche 911 Turbo S Coupe, which represents the 992 generation, is equipped with a 3.8-liter twin-turbocharged flat-six engine. The engine displacement of this particular model is approximately 3,745 cc. ',
    speed: '330 km/h',
    seats: '2',
    engine: '3.8 TT',
    stars: '4.9',
    price: 25000,
    priceW: 170000,
    priceM: 740000,
    date: '2021',
    mileage: '10,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '3745',
    color: 'Grey',
    color1: 'assets/images/black.png',
    color2: 'assets/images/green.png',
    color3: 'assets/images/blue.png',
    coord1: -20.4265360763728,
    coord2: 57.541869766308295,
    chooseC1: 'assets/images/porsche911c1.png',
    chooseC2: 'assets/images/porsche911c2.png',
    chooseC3: 'assets/images/porsche911c3.png',
  ),
  Book(
    brand: 'assets/images/minilogo.png',
    name: 'Mini Cooper',
    model: 'S Clubman 2020',
    location: 'MoVacances car Rentals, Bois Cheri',
    imageUrl: 'assets/images/miniS.png',
    imageUrl1: 'assets/images/miniS1.png',
    imageUrl2: 'assets/images/miniS2.png',
    description:
        'Mini has slimmed the Cooper Clubman trim range and engine lineup. The car benefits from exterior styling updates, and the list of standard features expands to include amenities such as LED taillights. Within the cabin, the 2020 Mini Cooper S Clubman gets a fresh range of leather trims and interior surfaces. Also, a new seven-speed dual-clutch automatic transmission is now standard.',
    speed: '210 km/h',
    seats: '5',
    engine: '1.6 DOHC',
    stars: '4.2',
    price: 1600,
    priceW: 11000,
    priceM: 43000,
    date: '2020',
    mileage: '66,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '1600',
    color: 'Red',
    color1: 'assets/images/green.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/black.png',
    coord1: -20.4265360763728,
    coord2: 57.541869766308295,
    chooseC1: 'assets/images/miniSc1.png',
    chooseC2: 'assets/images/miniSc2.png',
    chooseC3: 'assets/images/miniSc3.png',
  ),
  Book(
    brand: 'assets/images/hondalogo.png',
    name: 'Honda',
    model: 'Civic EK 1998',
    location: 'Vivéa Business Park, Moka',
    imageUrl: 'assets/images/hondacivicdx.png',
    imageUrl1: 'assets/images/hondacivicdx1.png',
    imageUrl2: 'assets/images/hondacivicdx2.png',
    description:
        'The Honda Civic EK3 has a very comfortable and engaging driving experience. It comes with a smooth manual transmission, with a very soft hydraulic clutch. The throttle response also demands your respect if you do not want to kill anyone who might be in front of you. The car is instantly playful, from the very first gear, and engaging the V-Tec at 4,000 RPMs just ups the ante.',
    speed: '190 km/h',
    seats: '5',
    engine: '1.6 D16',
    stars: '4.7',
    price: 900,
    priceW: 6000,
    priceM: 23000,
    date: '1998',
    mileage: '234,000 Km',
    trans: 'Manual',
    fuel: 'Petrol',
    cc: '1600',
    color: 'Red',
    color1: 'assets/images/black.png',
    color2: 'assets/images/white.png',
    color3: 'assets/images/yellow.png',
    coord1: -20.223752405064925,
    coord2: 57.53125163137671,
    chooseC1: 'assets/images/hondacivicdxc1.png',
    chooseC2: 'assets/images/hondacivicdxc2.png',
    chooseC3: 'assets/images/hondacivicdxc3.png',
  ),
  Book(
    brand: 'assets/images/hondalogo.png',
    name: 'Honda',
    model: 'Jazz 2023',
    location: 'Morcellement St Andre C.C, Port Louis',
    imageUrl: 'assets/images/hondajazz.png',
    imageUrl1: 'assets/images/hondajazz1.png',
    imageUrl2: 'assets/images/hondajazz2.png',
    description:
        'Honda made a splash in the B-segment when it launched the original Jazz nearly two decades ago. The concept of a hatchback with a sprinkling of multi-purpose vehicle versatility instantly took off.Its tallish roof and practical interior dimensions made for a companion that suited all manner of lifestyles, enhanced by features such as rear seats that could be configured in seemingly endless ways. ',
    speed: '180 km/h',
    seats: '5',
    engine: 'L12B',
    stars: '4.5',
    price: 1100,
    priceW: 7600,
    priceM: 30400,
    date: '2023',
    mileage: '54,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '1200',
    color: 'Dark Grey',
    color1: 'assets/images/red.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/grey.png',
    coord1: -20.067555664372684,
    coord2: 57.56944219459583,
    chooseC1: 'assets/images/hondajazzc1.png',
    chooseC2: 'assets/images/hondajazzc2.png',
    chooseC3: 'assets/images/hondajazzc3.png',
  ),
  Book(
    brand: 'assets/images/hyundailogo.png',
    name: 'Hyundai',
    model: 'Tucson A/T Ultimate 2023',
    location: 'Morcellement St Andre C.C, Port Louis',
    imageUrl: 'assets/images/hyundaitucson.png',
    imageUrl1: 'assets/images/hyundaitucson1.png',
    imageUrl2: 'assets/images/hyundaitucson2.png',
    description:
        'The 2023 Hyundai Tucson struts a cutting-edge style that stands out among its more sober- looking compact SUV competitors. That does not mean that the Tucson sacrifices practicality or affordability. It boasts both. Hyundai has taken the blanket approach with the Tucson, offering a wide variety of trims and powertrains—including a hybrid and plug-in hybrid, which we review separately—giving it broad appeal. ',
    speed: '200 km/h',
    seats: '5',
    engine: '2.0 DR',
    stars: '4.7',
    price: 1450,
    priceW: 10150,
    priceM: 40500,
    date: '2023',
    mileage: '11,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '2000',
    color: 'White',
    color1: 'assets/images/yellow.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/pink.png',
    coord1: -20.067555664372684,
    coord2: 57.56944219459583,
    chooseC1: 'assets/images/hyundaitucsonc1.png',
    chooseC2: 'assets/images/hyundaitucsonc2.png',
    chooseC3: 'assets/images/hyundaitucsonc3.png',
  ),
  Book(
    brand: 'assets/images/nissanlogo.png',
    name: 'Nissan',
    model: 'Rogue 2015',
    location: 'Les Barachois de Grand Gaube, Phase 2, Cashmir Rd, Grand Gaube',
    imageUrl: 'assets/images/nissanrogue.png',
    imageUrl1: 'assets/images/nissanrogue1.png',
    imageUrl2: 'assets/images/nissanrogue2.png',
    description:
        'The attractive and stylish 2015 Nissan Rogue is a compact crossover that offers seating for five or even seven passengers. It has a lot to offer for families, but the compact-crossover market is full of excellent choices so it is becoming harder and harder for vehicles to stand out in the crowd.',
    speed: '190 km/h',
    seats: '5',
    engine: '1.5 V.C.T',
    stars: '4.7',
    price: 1300,
    priceW: 9100,
    priceM: 36400,
    date: '2015',
    mileage: '205,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '1500',
    color: 'Grey',
    color1: 'assets/images/green.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/black.png',
    coord1: -20.015183073063714,
    coord2: 57.66971581972788,
    chooseC1: 'assets/images/nissanroguec1.png',
    chooseC2: 'assets/images/nissanroguec2.png',
    chooseC3: 'assets/images/nissanroguec3.png',
  ),
  Book(
    brand: 'assets/images/bmwlogo.png',
    name: 'BMW',
    model: 'X5 2015',
    location: 'MoVacances car Rentals, Bois Cheri',
    imageUrl: 'assets/images/bmwx5.png',
    imageUrl1: 'assets/images/bmwx51.png',
    imageUrl2: 'assets/images/bmwx52.png',
    description:
        'Back at the turn of the century, the BMW X5 was one of the few luxury SUVs available. Since then, it has continually been a go-to choice for shoppers who want their SUV to drive more like a sport sedan than a truck. The 2015 BMW X5, fresh off a redesign last year, stays true to that formula that honors the performance soul of the company while still providing the all-weather capability, added cargo space and elevated driving position that is of such great appeal to crossover owners.',
    speed: '260 km/h',
    seats: '5',
    engine: '3.0 VB',
    stars: '4.7',
    price: 3500,
    priceW: 24000,
    priceM: 97000,
    date: '2015',
    mileage: '130,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '3000',
    color: 'Black',
    color1: 'assets/images/white.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/grey.png',
    coord1: -20.4266064558371,
    coord2: 57.54189122398001,
    chooseC1: 'assets/images/bmwx5c1.png',
    chooseC2: 'assets/images/bmwx5c2.png',
    chooseC3: 'assets/images/bmwx5c3.png',
  ),
  Book(
    brand: 'assets/images/nissanlogo.png',
    name: 'Nissan',
    model: 'GTR R35',
    location: 'MoVacances car Rentals, Bois Cheri',
    imageUrl: 'assets/images/nissangtr.png',
    imageUrl1: 'assets/images/nissangtr1.png',
    imageUrl2: 'assets/images/nissangtr2.png',
    description:
        'Nissan GT-R began hitting dealer lots 15 years ago and quickly earned the nickname “Godzilla.” This year sees the return of the mid-tier T-Spec model, which slots between the Premium and full-blown Nismo versions. The twin-turbocharged 3.8-liter V-6 engine still makes 600 horsepower under the hood of Nismo units, while Premium and T-Spec models see a tamer yet still potent 565 ponies. The usual performance bits are still present, too, including e-adjustable Bilstein dampers and Brembo brakes with carbon-ceramic setups for the performance-focused variants.',
    speed: '315 km/h',
    seats: '4',
    engine: '3.8 VR38',
    stars: '5.0',
    price: 15000,
    priceW: 105000,
    priceM: 415000,
    date: '2021',
    mileage: '11,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '3800',
    color: 'Grey',
    color1: 'assets/images/green.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/yellow.png',
    coord1: -20.4266064558371,
    coord2: 57.54189122398001,
    chooseC1: 'assets/images/nissangtrc1.png',
    chooseC2: 'assets/images/nissangtrc2.png',
    chooseC3: 'assets/images/nissangtrc3.png',
  ),
  Book(
    brand: 'assets/images/nissanlogo.png',
    name: 'Nissan',
    model: 'NV200',
    location: 'Le Cap Car Hire Ltd, Cap Malheureux',
    imageUrl: 'assets/images/nissannv200.png',
    imageUrl1: 'assets/images/nissannv2001.png',
    imageUrl2: 'assets/images/nissannv2002.png',
    description:
        'The NV200 is a very slim, compact van that runs on relatively small wheels for maximum manoeuvrability around town. However, this does mean the ride is a bit bouncy on the open road, while the van isn’t really suited to long motorway journeys.',
    speed: '190 km/h',
    seats: '7',
    engine: '1.5 D.C.I',
    stars: '4.6',
    price: 1200,
    priceW: 8400,
    priceM: 33500,
    date: '2016',
    mileage: '72,000 Km',
    trans: 'Automatic',
    fuel: 'Diesel',
    cc: '1500',
    color: 'Black',
    color1: 'assets/images/red.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/white.png',
    coord1: -19.985089678040048,
    coord2: 57.612981231368316,
    chooseC1: 'assets/images/nissannv200c1.png',
    chooseC2: 'assets/images/nissannv200c2.png',
    chooseC3: 'assets/images/nissannv200c3.png',
  ),
  Book(
    brand: 'assets/images/toyotalogo.png',
    name: 'Toyota',
    model: 'Yaris 2017',
    location: 'Le Cap Car Hire Ltd, Cap Malheureux',
    imageUrl: 'assets/images/toyotayaris.png',
    imageUrl1: 'assets/images/toyotayaris1.png',
    imageUrl2: 'assets/images/toyotayaris2.png',
    description:
        'The Toyota Yaris is one of the brand’s best-selling models, and in the UK it competes with the hugely popular Ford Fiesta, Vauxhall Corsa and VW Polo models in the supermini class. It’s easy to see why Toyota has refreshed the car with this new facelifted version, then. Toyota has also updated the interior with some new materials, although the design is very similar to the previous car.  ',
    speed: '210 km/h',
    seats: '5',
    engine: '1.5 L-4',
    stars: '4.5',
    price: 1200,
    priceW: 8400,
    priceM: 33500,
    date: '2017',
    mileage: '110,000',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '1500',
    color: 'Red',
    color1: 'assets/images/yellow.png',
    color2: 'assets/images/black.png',
    color3: 'assets/images/white.png',
    coord1: -19.98514009184429,
    coord2: 57.61295977369659,
    chooseC1: 'assets/images/toyotayarisc1.png',
    chooseC2: 'assets/images/toyotayarisc2.png',
    chooseC3: 'assets/images/toyotayarisc3.png',
  ),
  Book(
    brand: 'assets/images/toyotalogo.png',
    name: 'Toyota',
    model: 'Corolla 2020',
    location: 'Le Cap Car Hire Ltd, Cap Malheureux',
    imageUrl: 'assets/images/toyotacorolla.png',
    imageUrl1: 'assets/images/toyotacorolla1.png',
    imageUrl2: 'assets/images/toyotacorolla2.png',
    description:
        ' The Corolla ride quality is smooth, and the front seats are comfortable. Whether you are tall or small, there are enough adjustments and sufficient range within those adjustments to find your preferred position.Road noise increases noticeably on coarse asphalt surfaces, and you will hear some extra wind noise around the mirrors at highway speeds. The noise is not offensive, and the cabin is otherwise pleasantly quiet Interior8.0/10',
    speed: '210 km/h',
    seats: '5',
    engine: '2.0 L-B',
    stars: '4.7',
    price: 1300,
    priceW: 9100,
    priceM: 36400,
    date: '2020',
    mileage: '100,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '2000',
    color: 'Grey',
    color1: 'assets/images/red.png',
    color2: 'assets/images/green.png',
    color3: 'assets/images/white.png',
    coord1: -19.98514009184429,
    coord2: 57.61295977369659,
    chooseC1: 'assets/images/toyotacorollac1.png',
    chooseC2: 'assets/images/toyotacorollac2.png',
    chooseC3: 'assets/images/toyotacorollac3.png',
  ),
  Book(
    brand: 'assets/images/bmwlogo.png',
    name: 'BMW',
    model: '8 Series Gran Coupe',
    location: 'MoVacances car Rentals, Bois Cheri',
    imageUrl: 'assets/images/bmw8.png',
    imageUrl1: 'assets/images/bmw81.png',
    imageUrl2: 'assets/images/bmw82.png',
    description:
        'The 8 Series Gran Coupe arrives with an opportunity to grasp, too. The latest Eight – with big, pop-up headlight-equipped shoes to fill – has so far left us a little nonplussed. It’s a wonderful object, alright, but it’s simply too stiff to be a plush, distance-decimating GT car, while too big and bloated to act the sports car. We’re not sure which rivals it’s taking aim at, and it triumphs over nothing as a result.',
    speed: '280 km/h',
    seats: '4',
    engine: '3.0 V8',
    stars: '5.0',
    price: 15000,
    priceW: 105000,
    priceM: 420000,
    date: '2021',
    mileage: '20000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '3000',
    color: 'Blue',
    color1: 'assets/images/red.png',
    color2: 'assets/images/purple.png',
    color3: 'assets/images/black.png',
    coord1: -20.426475751092042,
    coord2: 57.541912681651716,
    chooseC1: 'assets/images/bmw8c1.png',
    chooseC2: 'assets/images/bmw8c2.png',
    chooseC3: 'assets/images/bmw8c3.png',
  ),
  Book(
    brand: 'assets/images/audilogo.png',
    name: 'Audi',
    model: 'S8 2015',
    location: 'Port Louis Gymkhana, Frère Felix De Valois Street, Port Louis',
    imageUrl: 'assets/images/audis8.png',
    imageUrl1: 'assets/images/audis81.png',
    imageUrl2: 'assets/images/audis82.png',
    description:
        'Audi sedans, even those with an “S” in their names, are usually the epitome of understated style. But the 2016 S8 Plus that recently showed up for our first full test wore a sinister combination of matte-silver paint, blackout body trim, and carbon-fiber accents. The bad-ass livery wouldn’t make it any faster, of course, but it certainly suits the car’s persona, offering a hint at the stone-cold seriousness with which the S8 Plus comports itself, bristling as it now does with a staggering 605 horsepower and 553 lb-ft of torque under the hood.',
    speed: '280 km/h',
    seats: '4',
    engine: '4.0 V8',
    stars: '5.0',
    price: 20000,
    priceW: 140000,
    priceM: 560000,
    date: '2015',
    mileage: '52,000 Km',
    trans: 'Automatic',
    fuel: 'Petrol',
    cc: '4000',
    color: 'Black',
    color1: 'assets/images/orange.png',
    color2: 'assets/images/blue.png',
    color3: 'assets/images/white.png',
    coord1: -20.171420931898588,
    coord2: 57.51046084856929,
    chooseC1: 'assets/images/audis8c1.png',
    chooseC2: 'assets/images/audis8c2.png',
    chooseC3: 'assets/images/audis8c3.png',
  ),
];
